; ============================================================
;  KaBullto RC — template mínimo
;  Plataforma: ESP32-S3
;  Framework: Arduino
; ============================================================

[env:esp32-s3-devkitm-1]
platform  = espressif32
board     = esp32-s3-devkitm-1
framework = arduino

; Dependencias externas (baixadas automaticamente pelo PlatformIO)
lib_deps =
    asukiaaa/XboxSeriesXControllerESP32_asukiaaa@^1.0.9

; Upload via cabo USB (padrão)
; Para ativar OTA, comente as linhas acima e descomente abaixo:
; upload_protocol = espota
; upload_port     = 192.168.4.1
; upload_flags    = --port=3232
